name: zoncan
description: A software for generating invoices and accounting system

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta

environment:
  sdk: ">=2.17.3 <3.0.0"

#!#########################
dependencies:
  bot_toast: ^4.0.2
  eva_icons_flutter: ^3.1.0
  fast_i18n: ^5.12.6
  floy:
    path: /home/mohrazium/Projects/Flutter/Plugins/Floy-Workspace/floy/
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  flutter_multi_formatter: ^2.5.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.0
  flutter_triple: ^1.2.7+2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  loading_animation_widget: ^1.1.0+5
  logging: ^1.0.1
  mobx_triple: ^1.1.3+1
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  path: ^1.8.0
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  persian_datetime_picker: ^2.5.0
  persian_tools: ^1.0.1
  pointycastle: ^3.6.0
  shamsi_date: ^1.0.1
  shared_preferences: ^2.0.15
  syncfusion_flutter_core: ^20.1.47
  syncfusion_flutter_datagrid: ^20.1.47
  syncfusion_localizations: ^20.1.47

#!#########################
dev_dependencies:
  build_runner: ^2.1.11

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  objectbox_generator: ^1.6.0

#!#########################
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel/sahel.ttf
        - asset: assets/fonts/sahel/sahel_bold.ttf
        - asset: assets/fonts/sahel/sahel_black.ttf
        - asset: assets/fonts/sahel/sahel_light.ttf
        - asset: assets/fonts/sahel/sahel_semi_bold.ttf

objectbox:
  output_dir: common/src/database/generated
